--
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks: 
  	- name: Copy war file to tomcat
  	  copy:
  	  	src: "/var/snap/jenkins/4865/workspace/MavenWeb/target/MavenWeb.war"
  	  	dest: "/opt/tomcat/webapps/MavenWeb.war"
  	  	remote_src: no
  	- name: Restart Tomcat
  	  systemd:
  	  	name: tomcat
  	  	state: restart
